Dalmo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from my_app.views import page_not_found, handler_500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('oauth/', include('social_django.urls', namespace='social')),
    path('', include('my_app.urls')),
    path('', include('inbox.urls')),
    path('', include('account.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = page_not_found

LOGIN_URL = 'login'
LOGOUT_URL = 'logout'
LOGIN_REDIRECT_URL = 'home'

account/urls.py
from django.urls import path
from . import views

from django.contrib.auth import views as auth_views

urlpatterns = [

    path('', views.home, name='base'),

    path('home/', views.home, name='home'),

    path('signup/', views.signup, name='signup'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.logout_user, name='logout'),

    path('profile/', views.profile, name='profile'),
    path('accounts/profile/', views.profile),
    path('profile/notifications/', views.notifications, name='notifications'),
    path('profile/get/notifications/', views.get_notifications),
    path('update/profilepic/', views.profile_pic_update, name='update/profilepic'),
    path('update/details', views.profile, name='update/details'),

    path('api/messageUs/', views.api_message_us),
    path('api/create/topic/', views.api_home_topic_form),

    path('notification/delete/<str:note_ID>/', views.delete_notification),

    path('account/friends/', views.add_friends, name='friends'),

    path('api/send_friend_request/<str:username>/', views.api_add_friend_request),
    path('api/add/<str:username>/<str:notification_ID>/', views.api_add_remove_friend),
    path('api/remove/<str:username>/<str:notification_ID>/', views.api_add_remove_friend),

]

urlpatterns += [
    path('api/users/', views.Api_All_Users.as_view()),
    path('api/users/<str:user_name>/', views.Api_User_Details.as_view()),
]

urlpatterns += [
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='account/password/password_reset.html'),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='account/password/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='account/password/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='account/password/password_reset_complete.html'),
         name='password_reset_complete'),
]

my_app/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [

    path('myadmin/', views.my_admin, name='myadmin'),

    # path('api/create/topic/', views.api_home_topic_form, name='api/create/topic/homepage/'),

    path('read_reply_email_message/<int:_id>/', views.read_reply_email_message),
    path('delete_reply_topic_comment_question/<int:_id>/', views.delete_reply_comment_topic_question),
    path('hide_show_reply_comment/<int:_id>/', views.hide_show_reply_comment_topic_question),

    path('create/', views.create, name='create'),
    path('api/createTopic/', views.api_create_quiz, name='api/createTopic'),
    path('api/create/topics_subtopics/', views.api_topic_subtopic_render, name='api/create'),
    path('join/', views.join, name='join'),
    path('discussion_join/', views.join_via_code, name='discussion_join'),

    path('comments/<str:reply_id>/', views.comments_api),

    path('c19/', views.c19, name='c19'),
    path('wnews/', views.wnews, name='wnews'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),

    path('trial', views.trial_loader, name='trial'),

    path('discuzz/<str:discussion_details>/', views.discuzz, name='discuzz'),

    path('discuzz_api/<str:discussion_details>/', views.reply_api),

    path('api/discuzz/<str:discussion_details>/', views.api_discuzz_details, name='api_discuzz'),
    path('api/all_numbers/', views.api_my_admin, name='api_all_numbers'),
    path('api/participants/<str:discussion_code>/', views.participants),

    path('like/', views.like, name='like'),
    path('dislike/', views.dislike, name='dislike'),
    path('comment/', views.all_comments_api, name='comment'),
    path('emails/', views.email, name='emails'),

    path('prog/', views.progpage, name='prog'),

]

urlpatterns += [
    path('mapi/questions/', views.quiz_api.as_view()),
    path('mapi/questions/<str:id_>/', views.quiz_api_single),
    path('mapi/replies/', views.reply_api),
    path('mapi/comments/', views.comment_api),
]

account/models.py
import jsonfield
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from multiselectfield import MultiSelectField


class UserExtension(models.Model):
    sheet = (
        ('prettify', 'default'),
        ('desert', 'desert'),
        ('doxy', 'doxy'),
        ('sons-of-obsidian', 'sons-of-obsidian'),
        ('sunburst', 'sunburst')

    )
    mode = (
        ('light', 'light'),
        ('dark', 'dark')
    )
    gender_choices = (
        ('male', 'Male'),
        ('female', 'Female'),
        ('other', 'Other')
    )
    languages = (
        ('Java', 'Java'),
        ('Javascript', 'Javascript'),
        ('C', 'C'),
        ('C#', 'C#'),
        ('C++', 'C++'),
        ('Objective-c', 'Objective-C'),
        ('Php', 'Php'),
        ('Python', 'Python'),
        ('Javascript', 'Javascript'),
        ('Ruby', 'Ruby'),
        ('Perl', 'Perl'),
        ('Clojure', 'Clojure'),
        ('Scala', 'Scala'),
        ('Go', 'Go'),
        ('R*', 'R*'),
        ('Tcl', 'Tcl'),
        ('Lua', 'Lua'),
        ('Bash', 'Bash'),
        ('Visual Basic.NET', 'Visual Basic.NET'),
        ('Haskel', 'Haskel'),
    )
    user = models.OneToOneField(User, default=None, on_delete=models.CASCADE, blank=True, null=True)
    style_sheet = models.TextField(null=True, blank=True, default=sheet[1][1], choices=sheet)
    mode_sheet = models.TextField(null=True, blank=True, default=mode[1][0], choices=mode)
    profile_pic = models.ImageField(blank=True,
                                    null=True,
                                    default='/default.png')
    friends = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='friends')
    friend_requests = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='friend_requests')

    location = models.CharField(default='', null=True, blank=True, max_length=100)
    phone_number = models.CharField(default='+254 7 06 522 473', null=True, blank=True, max_length=20)
    gender = models.TextField(default='Not set', blank=True, null=True, choices=gender_choices, max_length=10)
    bio = models.CharField(default='I love discuzz since it is the best discussion platform.',
                           max_length=200, blank=True, null=True)
    programming_languages = MultiSelectField(choices=languages, max_choices=20, blank=True, null=True)

    # notifications = jsonfield.JSONField(default=[{"id": 0, "type": "visiting message", "by": "Discuzz"}])
    # notifications = models.JSONField(default=[()], blank=True, null=True)

    hobbies = models.CharField(blank=True, null=True, max_length=200)

    status = models.TextField(blank=True, null=True, max_length=200, default='offline')

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            UserExtension.objects.create(user=instance)
            instance.userextension.save()

            # post_save.connect(UserExtension, sender=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        UserExtension.objects.get_or_create(user=instance)
        instance.userextension.save()


class Notification(models.Model):
    kind = models.TextField(default='welcome', blank=True, null=True)
    by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='notification', blank=True, null=True)
    to = models.ForeignKey(User, on_delete=models.CASCADE, related_name='notification_to', blank=True, null=True)
    where = models.TextField(blank=True, null=True)
    question_code = models.TextField(blank=True, null=True)
    topic = models.TextField(blank=True, null=True)
    question = models.TextField(blank=True, null=True)
    when = models.DateTimeField(auto_now_add=True)

my_app/models.py
import json

# from django.contrib.postgres.fields import JSONField
import jsonfield
from django.conf import settings
from django.core.serializers.json import DjangoJSONEncoder
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, User

# Create your models here.
from django.db.models.signals import post_save
from django.dispatch import receiver

from multiselectfield import MultiSelectField


class Create(models.Model):
    choices = (
        ('visible', 'visible'),
        ('hidden', 'hidden')
    )

    topic = models.CharField(max_length=50)
    admin = models.ForeignKey(User, default=None, on_delete=models.SET_NULL, blank=True, null=True)
    paymentMode = models.CharField(max_length=20, null=True, blank=True)
    paymentCode = models.CharField(max_length=20)
    subtopic = models.CharField(max_length=100)
    description = models.CharField(max_length=200)
    question = models.CharField(max_length=1000)
    discussionCode = models.CharField(max_length=100, default='100NO00DISCUSSION001yet11')
    createTime = models.DateTimeField(auto_now_add=True)

    status = models.TextField(choices=choices, default=choices[0][1], blank=True, null=True)

    def __str__(self):
        return self.topic


class Discuzz(models.Model):
    choices = (
        ('visible', 'visible'),
        ('hidden', 'hidden')
    )

    discussion_code = models.ForeignKey(Create, default=None, on_delete=models.SET_NULL, blank=True, null=True)
    reply = models.TextField(max_length=6000)
    username = models.ForeignKey(User, default=None, on_delete=models.SET_NULL, blank=True, null=True)

    likes = models.ManyToManyField(User, related_name='likes', blank=True)
    dislikes = models.ManyToManyField(User, related_name='dislikes', blank=True)
    comments = models.ManyToManyField(User, related_name='comments', blank=True)

    status = models.TextField(choices=choices, default=choices[0][1], blank=True, null=True)

    reply_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.discussion_code.discussionCode


class Comment(models.Model):
    choices = (
        ('visible', 'visible'),
        ('hidden', 'hidden')
    )

    commented_to = models.ForeignKey(Discuzz, default=None, on_delete=models.CASCADE, blank=True, null=True)
    commented_by = models.ForeignKey(User, default=None, on_delete=models.SET_NULL, blank=True, null=True)
    comment = models.TextField(max_length=500)
    commented_on = models.DateTimeField(auto_now_add=True)
    status = models.TextField(choices=choices, default=choices[0][1], blank=True, null=True)


class SendEmail(models.Model):
    choices = (
        ('unread', 'unread'),
        ('read', 'read')
    )
    state = (
        ('reply', 'reply'),
        ('replied', 'replied')
    )
    email = models.ForeignKey(User, default=None, on_delete=models.CASCADE, blank=True, null=True)
    update = models.CharField(max_length=2000)
    updateTime = models.DateTimeField(auto_now_add=True)
    status = models.TextField(choices=choices, default=choices[0][1], blank=True)
    state = models.TextField(choices=state, default=state[0][1], blank=True)

    def __str__(self):
        return self.email.email


class Topic(models.Model):
    choices = (
        ('visible', 'visible'),
        ('hidden', 'hidden')
    )

    user = models.ForeignKey(User, default=None, on_delete=models.CASCADE, blank=True, null=True)
    topic = models.CharField(max_length=50)
    subtopic = models.CharField(max_length=50)
    status = models.TextField(choices=choices, default=choices[0][1], blank=True, null=True)

    def __str__(self):
        return self.topic


class Syntax(models.Model):
    topic = models.CharField(max_length=50, blank=True, null=True)

    def __str__(self):
        return self.topic

account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import User
from django.contrib.auth.views import LoginView

from .models import UserExtension


class UserSignUp(UserCreationForm):
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'minlength': 9}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'minlength': 9}))

    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']


class UserLogin(LoginView):
    class Meta:
        fields = ['username', 'password']


class PicForm(forms.ModelForm):
    style_sheet = forms.Select()
    mode_sheet = forms.RadioSelect()
    location = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), label='Location')
    phone_number = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), label='Location:')
    bio = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))
    hobbies = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    gender = forms.Select()
    programming_languages = forms.CheckboxSelectMultiple()

    class Meta:
        model = UserExtension
        fields = ['style_sheet',
                  'mode_sheet',
                  'location',
                  'phone_number',
                  'bio',
                  'hobbies',
                  'gender',
                  'programming_languages',
                  ]
        print(fields)

templates/my_app/account/login.html
{% extends 'base.html' %} {% block content %}
<div class="row">
    <div class="col-md-3 col-sm-12"></div>
    <div class="col-md-6 col-sm-12 form">
        <div class="jumbotron">
            <div class="login_form">
                <h4 class="text-center">Log in to your account</h4>
                {% for message in messages %}
                <p class="text-success text-danger">{{ message }}</p>
                {% endfor %}
                <form method="POST" action="">
                    {% csrf_token %}
                    <fieldset>
                        <div class="form-row input">
                            <div class="form-group col-md-12 inputBox">
                                <label for="uid">Username</label>
                                <input type="text" class="" name="uid" id="uid" placeholder="Username">
                            </div>
                            <div class="form-group col-md-12 inputBox">
                                <label for="pwd">Password</label>
                                <input type="password" class="" name="pwd" id="pwd" placeholder="Password">
                            </div>
                            <div class="form-group col-md-12 inputBox">
                                <input type="submit" name="" value="Sign In">
                            </div>
                        </div>
                    </fieldset>
                </form>
                <script>
                    let form_inputs = document.getElementsByTagName("input");
                    form_inputs[1].placeholder = 'Username';
                    form_inputs[2].placeholder = 'Password';
                </script>
                <div class="help">
                    <p>Don't have an account? <a href="{% url 'signup' %}">Signup</a> </p>
                    <p>Forgot password?
                        <a href="{% url 'signup' %}"> <span> Click here </span> </a>
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-3 col-sm-12"></div>
</div>
</div>
{% endblock %}

templates/my_app/account/profile.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="jumbotron profile">
    <h3 class="text-center"> <i class="fa fa-user" aria-hidden="true"></i> Welcome to your account , {{ user.username }}</h3>

    <div class="row">
        <div class="col-md-3 col-sm-12">
            <h4 class="text-center"> Profile picture </h4>
            <hr>
            <div class="img">
                <img src="{% static 'biz.jpg' %}" alt="{{ user.usernme }}">
                <p class="text-center user"> {{user.username}} </p>
            </div>
            <div class="contents">
                <button class="btn btn-info">Edit profile picture</button>
            </div>
        </div>
        <div class="col-md-3 col-sm-12">
            <h4 class="text-center"> Account details </h4>
            <hr>
            <p> First name: <span class="float-right">{{ user.first_name }}</span> </p>
            <p> Last name: <span class="float-right">{{ user.last_name}}</span> </p>
            <p> Email: <span class="float-right">{{ user.email }}</span> </p>
            <p> Username: <span class="float-right">{{ user.username }}</span> </p>
            <div class="contents">
                <button class="btn btn-info">Edit your account information</button>
            </div>
        </div>
        <div class="col-md-6 col-sm-12">
            <h4 class="text-center"> Your Quizes </h4>
            <hr>
            <div class="row">
                <div class="col">

                    {% for code in your_discussions %} {% if code.admin == user.username %} {% if code.discussionCode == '' or none %}
                    <p>You have no discussions yet</p>
                    {% else %}
                    <div class="row">
                        <div class="col-md-10 col-xs-10">
                            <a href="/discuzz/{{code.discussionCode}}">
                                <span class="s-text">{{ code.discussionCode }}</span>
                            </a>
                        </div>
                        <div class="col-md-2 col-sm-2">
                            <button class="btn btn-warning btn-sm" title="delete"> <i class="fa fa-trash" aria-hidden="true"></i> </button>
                            <button class="btn btn-warning btn-sm" title="share"> <i class="fa fa-share" aria-hidden="true"></i> </button>
                        </div>
                    </div>
                    <hr> {% endif %} {% endif %} {% endfor %}
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12 col-sm-12">
            <h4 class="text-center"> Your conributions </h4>
            <hr>
            <p>All your messages to various discussions</p>

            <div class="row">
                <div class="col-md-3 col-sm-12"></div>
                <div class="col-md-6 col-sm-12 h100">
                    {% for ty in t %} {% if ty.username == user.username %}

                    <details>
                        <summary> <i class="fa fa-calendar" aria-hidden="true"></i>{{ ty.reply_time }} <a class="disc-message" href="/discuzz/{{ty.discussion_code}}#{{user.username}}">{{ ty.discussion_code }} </a> </summary>
                        <p> {{ ty.reply }} </p>
                    </details>

                    {% endif %} {% endfor %}
                </div>
                <div class="col-md-3 col-sm-12"></div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/my_app/account/signup.html
{% extends 'base.html' %} {% block content %}
<div class="row">
    <div class="col-md-3 col-sm-12"></div>
    <div class="col-md-6 col-sm-12 form">
        <div class="jumbotron">
            <div class="login_form">
                <h4 class="text-center">Create a new account</h4>
                {% for message in messages %}
                <p class="text-success text-danger">{{ message }}</p>
                {% endfor %}
                <form method="POST" action="">
                    {% csrf_token %}
                    <fieldset>
                        <div class="form-row input">
                            <div class="form-group col-md-12 inputBox">
                                <label for="id_first_name">{{ form.first_name.label }}</label> {{ form.first_name }}
                            </div>

                            <div class="form-group col-md-12 inputBox">
                                <label for="id_last_name">{{ form.last_name.label }}</label> {{ form.last_name }}
                            </div>

                            <div class="form-group col-md-12 inputBox">
                                <label for="id_username">{{ form.username.label }}</label> {{ form.username }}
                            </div>

                            <div class="form-group col-md-12 inputBox">
                                <label for="id_email">{{ form.email.label }}</label> {{ form.email }}
                            </div>

                            <div class="form-group col-md-12 inputBox">
                                <label for="id_password1">{{ form.password1.label }}</label> {{ form.password1 }}
                            </div>

                            <div class="form-group col-md-12 inputBox">
                                <label for="id_password2">{{ form.password2.label }}</label> {{ form.password2 }}
                            </div>

                            <div class="form-group col-md-12 inputBox">
                                <input type="submit" name="" value="Sign Up">
                            </div>

                        </div>
                    </fieldset>
                </form>
                <div>
                    {{ form.errors }}
                </div>
                <div class="help">
                    <p>Already have an account? <a href="{% url 'login' %}">Login</a> </p>
                </div>
                <script>
                    let form_inputs = document.getElementsByTagName("input");
                    form_inputs[1].placeholder = 'First name';
                    form_inputs[2].placeholder = 'Last name';
                    form_inputs[3].placeholder = 'Username';
                    form_inputs[4].placeholder = 'Email';
                    form_inputs[5].placeholder = 'Password';
                    form_inputs[6].placeholder = 'Repeat password';

                    for (let fields in form_inputs) {
                        form_inputs[fields].className = "form-control";
                    }
                </script>
            </div>
        </div>
    </div>
    <div class="col-md-3 col-sm-12"></div>
</div>
</div>
{% endblock %}